import streamlit as st
import string
import random

def generate_password(length, use_digits=True, use_letters=True, use_special=True):
    character_list = ""
    if use_digits:
        character_list += string.digits
    if use_letters:
        character_list += string.ascii_letters
    if use_special:
        character_list += string.punctuation
    if not (use_digits or use_letters or use_special):
        raise ValueError("At least one character set must be selected.")

    return ''.join(random.choices(character_list, k=length))

def about_us():
    st.title("About Us")
    st.write("""
    Welcome to the Random Password Generator app! We're dedicated to providing a simple and secure solution for generating random passwords tailored to your needs. Our goal is to empower users like you to create strong and unique passwords, enhancing the security of your online accounts.

    ### Why Use Random Passwords?

    Random passwords generated by our app offer several key benefits:

    - **Security**: Random passwords are harder to guess, reducing the risk of unauthorized access to your accounts.
    - **Uniqueness**: Each password generated is unique, decreasing the likelihood of password reuse across multiple accounts.
    - **Customization**: Tailor your password by choosing the length and including specific character sets, such as digits, letters, and special characters.

    ### How to Use

    Simply specify the desired length of your password and select the character sets you'd like to include. Click the "Generate Password" button, and voila! You'll receive a strong, random password ready to use.

    ### About Streamlit

    This app is built using Streamlit, a powerful Python library for creating interactive web applications with ease. Streamlit allows us to quickly turn our Python scripts into dynamic web apps, making it simple to share our tools and insights with the world.

    Enjoy using our Random Password Generator, and stay secure online!

    - The Random Password Generator Team
    """)

def main():
    st.title("Random Password Generator")

    length = st.number_input("Enter password length:", min_value=1, step=1, value=8)

    use_digits = st.checkbox("Include Digits (0-9)", value=True)
    use_letters = st.checkbox("Include Letters (A-Z, a-z)", value=True)
    use_special = st.checkbox("Include Special Characters", value=True)

    if st.button("Generate Password"):
        try:
            password = generate_password(length, use_digits, use_letters, use_special)
            st.success("Your random password is: " + password)
        except ValueError as ve:
            st.error("Error: " + str(ve))

    about_us()

if __name__ == "__main__":
    main()
