import streamlit as st
import random
import string

st.title("Bano Qabil")

st.sidebar.markdown("""
    <div style="display: flex; justify-content: center;">
        <img src="https://banoqabil.pk/media/logo.png" width="200">
    </div>
""", unsafe_allow_html=True)

def generate_password(length, use_uppercase, use_numbers, use_special):
    characters = string.ascii_lowercase
    if use_uppercase:
        characters += string.ascii_uppercase
    if use_numbers:
        characters += string.digits
    if use_special:
        characters += string.punctuation

    password = ''.join(random.choice(characters) for i in range(length))
    return password

def main():
    st.sidebar.title("Navigation")
    tab = st.sidebar.radio("", ["Home", "About us", "Contact us"])

    if tab == "Home":
        st.title("Password Generator")
        length = st.slider("Select password length", 6, 30, 12)
        use_uppercase = st.checkbox("Include Uppercase Letters")
        use_numbers = st.checkbox("Include Numbers")
        use_special = st.checkbox("Include Special Characters")

        if st.button("Generate Password"):
            password = generate_password(length, use_uppercase, use_numbers, use_special)
            st.success("Your generated password is:")
            st.write(password)
            
   elif "about_us"():
    st.title("About Us")
    st.write("""
    Welcome to the Random Password Generator app! We're dedicated to providing a simple and secure solution for generating random passwords tailored to your needs. Our goal is to empower users like you to create strong and unique passwords, enhancing the security of your online accounts.

    ### Why Use Random Passwords?

    Random passwords generated by our app offer several key benefits:

    - **Security**: Random passwords are harder to guess, reducing the risk of unauthorized access to your accounts.
    - **Uniqueness**: Each password generated is unique, decreasing the likelihood of password reuse across multiple accounts.
    - **Customization**: Tailor your password by choosing the length and including specific character sets, such as digits, letters, and special characters.

    ### How to Use

    Simply specify the desired length of your password and select the character sets you'd like to include. Click the "Generate Password" button, and voila! You'll receive a strong, random password ready to use.

    ### About Streamlit

    This app is built using Streamlit, a powerful Python library for creating interactive web applications with ease. Streamlit allows us to quickly turn our Python scripts into dynamic web apps, making it simple to share our tools and insights with the world.

    Enjoy using our Random Password Generator, and stay secure online!

    - The Random Password Generator Team
    """)
        
    elif tab == "Contact us":
        st.title("Contact Us")
        st.write("Email: www.yaseenkhan2126@gmail.com")

if __name__ == "__main__":
    main()
